Repository hacf-fr/meteofrance-api, pull requests merged in 2020-10, with the labels that each got.

#35 Activate Dependabot on the repository
  .github/dependabot.yml
Labels: ci, dependencies

#34 Add automatic publish to PyPI workflow with automatic release note
  .github/release-drafter.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  src/meteofrance/__init__.py
  src/meteofrance/const.py
Labels: ci

#50 Fix typing-extension dependencies according to Python version
  poetry.lock
  pyproject.toml
Labels: bug

#33 Improve documentation
  .darglint
  .flake8
  CONTRIBUTING.md
  CONTRIBUTING.rst
  LICENSE.rst
  README.md
  README.rst
  docs/conf.py
  docs/contributing.rst
  docs/index.rst
  docs/license.rst
  docs/reference.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  src/meteofrance/client.py
  src/meteofrance/exceptions.py
  src/meteofrance/helpers.py
  src/meteofrance/model/__init__.py
  src/meteofrance/model/forecast.py
  src/meteofrance/model/picture_of_the_day.py
  src/meteofrance/model/place.py
  src/meteofrance/model/rain.py
  src/meteofrance/model/warning.py
  src/meteofrance/session.py
Labels: documentation

#57 Add HACF and Discord links when creating a new issue
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#64 Retrofit coockiecutter-hypermodern-python 2020.10.15 template
  .cookiecutter.json
  .flake8
  .gitattributes
  .github/workflows/constraints.txt
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .gitignore
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.rst
  CONTRIBUTING.rst
  README.rst
  codecov.yml
  docs/codeofconduct.rst
  docs/conf.py
  docs/contributing.rst
  docs/index.rst
  docs/requirements.txt
  mypy.ini
  noxfile.py
  poetry.lock
  pyproject.toml
  src/meteofrance/model/forecast.py
  src/meteofrance/model/place.py
  src/meteofrance/model/warning.py
  src/meteofrance/py.typed
  tests/__init__.py
Labels: ci, enhancement

#70 Rename Python package to meteofrance_api
  docs/reference.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  src/meteofrance_api/__init__.py
  src/meteofrance_api/__main__.py
  src/meteofrance_api/client.py
  src/meteofrance_api/const.py
  src/meteofrance_api/exceptions.py
  src/meteofrance_api/helpers.py
  src/meteofrance_api/model/__init__.py
  src/meteofrance_api/model/forecast.py
  src/meteofrance_api/model/picture_of_the_day.py
  src/meteofrance_api/model/place.py
  src/meteofrance_api/model/rain.py
  src/meteofrance_api/model/warning.py
  src/meteofrance_api/py.typed
  src/meteofrance_api/session.py
  tests/const.py
  tests/test_exception.py
  tests/test_forecast.py
  tests/test_helpers.py
  tests/test_integrations.py
  tests/test_picture_of_the_day.py
  tests/test_place.py
  tests/test_rain.py
  tests/test_session.py
  tests/test_warning.py
Labels: breaking, refactoring

#72 Fix typo: add a missing "a" in "availble"
  tests/test_integrations.py
Labels: bug
